using System.Text;
using GraphQL.SourceGenerators.Providers;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace GraphQL.SourceGenerators;

/// <summary>
/// Incremental source generator for AOT-compiled GraphQL schemas.
/// Generates partial class implementations for classes decorated with AOT attributes.
/// </summary>
[Generator]
public class AotSchemaGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Provider D: Get all candidate class declarations with AOT attributes
        var candidateClasses = SyntaxProvider.CreateCandidateProvider(context);

        // Register source output for each candidate class
        context.RegisterSourceOutput(candidateClasses, GenerateSource);
    }

    private static void GenerateSource(SourceProductionContext context, ClassDeclarationSyntax classDeclaration)
    {
        // Extract class information
        var className = classDeclaration.Identifier.Text;
        var namespaceName = GetNamespace(classDeclaration);

        // Generate the source code
        var sourceCode = GeneratePartialClass(namespaceName, className);

        // Add the generated source
        var fileName = $"{className}.g.cs";
        context.AddSource(fileName, SourceText.From(sourceCode, Encoding.UTF8));
    }

    private static string GetNamespace(ClassDeclarationSyntax classDeclaration)
    {
        // Walk up the syntax tree to find the namespace
        var namespaceDeclaration = classDeclaration.Ancestors()
            .OfType<BaseNamespaceDeclarationSyntax>()
            .FirstOrDefault();

        return namespaceDeclaration?.Name.ToString() ?? string.Empty;
    }

    private static string GeneratePartialClass(string namespaceName, string className)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(namespaceName))
        {
            sb.AppendLine($"namespace {namespaceName};");
            sb.AppendLine();
        }

        sb.AppendLine($"partial class {className}");
        sb.AppendLine("{");
        sb.AppendLine("    // generated code here");
        sb.Append("}");

        return sb.ToString();
    }
}
