version: 2
updates:

- package-ecosystem: "nuget"
  directory: "/"
  schedule:
    interval: "daily"
  ignore:
    - dependency-name: "GraphQL.Server.Ui.Altair"
    - dependency-name: "GraphQL.Server.Ui.GraphiQL"
    - dependency-name: "GraphQL.Server.Ui.Playground"
    - dependency-name: "GraphQL.Server.Ui.Voyager"

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
