using VerifySG = GraphQL.Analyzers.Tests.VerifiersExtensions.CSharpIncrementalGeneratorVerifier<
    GraphQL.SourceGenerators.AotSchemaGenerator>;

namespace GraphQL.Analyzers.Tests.SourceGenerators;

public class AotSchemaGeneratorTests
{
    [Fact]
    public async Task GeneratesPartialClass_ForQueryType()
    {
        const string source =
            """
            using GraphQL;
            using GraphQL.Types;

            namespace Sample;

            public class Query
            {
                public string Hello => "World";
            }

            [AotQueryType<Query>]
            public partial class MySchema : AotSchema
            {
                public MySchema() : base(null!, null!) { }
            }
            """;

        const string expectedGenerated =
            """
            // <auto-generated/>
            #nullable enable

            namespace Sample;

            partial class MySchema
            {
                // generated code here
            }
            """;

        await VerifySG.VerifyIncrementalGeneratorAsync(source, ("MySchema.g.cs", expectedGenerated));
    }

    [Fact]
    public async Task GeneratesPartialClass_ForMutationType()
    {
        const string source =
            """
            using GraphQL;
            using GraphQL.Types;

            namespace Sample;

            public class Mutation
            {
                public string DoSomething(string input) => input;
            }

            [AotMutationType<Mutation>]
            public partial class MySchema : AotSchema
            {
                public MySchema() : base(null!, null!) { }
            }
            """;

        const string expectedGenerated =
            """
            // <auto-generated/>
            #nullable enable

            namespace Sample;

            partial class MySchema
            {
                // generated code here
            }
            """;

        await VerifySG.VerifyIncrementalGeneratorAsync(source, ("MySchema.g.cs", expectedGenerated));
    }

    [Fact]
    public async Task GeneratesPartialClass_ForInputType()
    {
        const string source =
            """
            using GraphQL;
            using GraphQL.Types;

            namespace Sample;

            public class MyInput
            {
                public string Name { get; set; }
            }

            [AotInputType<MyInput>]
            public partial class MySchema : AotSchema
            {
                public MySchema() : base(null!, null!) { }
            }
            """;

        const string expectedGenerated =
            """
            // <auto-generated/>
            #nullable enable

            namespace Sample;

            partial class MySchema
            {
                // generated code here
            }
            """;

        await VerifySG.VerifyIncrementalGeneratorAsync(source, ("MySchema.g.cs", expectedGenerated));
    }

    [Fact]
    public async Task GeneratesPartialClass_ForOutputType()
    {
        const string source =
            """
            using GraphQL;
            using GraphQL.Types;

            namespace Sample;

            public class MyOutput
            {
                public string Name { get; set; }
            }

            [AotOutputType<MyOutput>]
            public partial class MySchema : AotSchema
            {
                public MySchema() : base(null!, null!) { }
            }
            """;

        const string expectedGenerated =
            """
            // <auto-generated/>
            #nullable enable

            namespace Sample;

            partial class MySchema
            {
                // generated code here
            }
            """;

        await VerifySG.VerifyIncrementalGeneratorAsync(source, ("MySchema.g.cs", expectedGenerated));
    }

    [Fact]
    public async Task GeneratesPartialClass_ForMultipleAttributes()
    {
        const string source =
            """
            using System;
            using GraphQL;
            using GraphQL.Types;

            namespace Sample;

            public class Query
            {
                public string Hello => "World";
            }

            public class MyInput
            {
                public string Name { get; set; }
            }

            [AotQueryType<Query>]
            [AotInputType<MyInput>]
            [AotTypeMapping<DateTime, DateTimeGraphType>]
            public partial class MySchema : AotSchema
            {
                public MySchema() : base(null!, null!) { }
            }
            """;

        const string expectedGenerated =
            """
            // <auto-generated/>
            #nullable enable

            namespace Sample;

            partial class MySchema
            {
                // generated code here
            }
            """;

        await VerifySG.VerifyIncrementalGeneratorAsync(source, ("MySchema.g.cs", expectedGenerated));
    }

    [Fact]
    public async Task GeneratesPartialClass_WithoutNamespace()
    {
        const string source =
            """
            using GraphQL;
            using GraphQL.Types;

            public class Query
            {
                public string Hello => "World";
            }

            [AotQueryType<Query>]
            public partial class MySchema : AotSchema
            {
                public MySchema() : base(null!, null!) { }
            }
            """;

        const string expectedGenerated =
            """
            // <auto-generated/>
            #nullable enable

            partial class MySchema
            {
                // generated code here
            }
            """;

        await VerifySG.VerifyIncrementalGeneratorAsync(source, ("MySchema.g.cs", expectedGenerated));
    }

    [Fact]
    public async Task NoGeneration_WhenNoAotAttributes()
    {
        const string source =
            """
            using GraphQL;
            using GraphQL.Types;

            namespace Sample;

            public class MySchema : Schema
            {
            }
            """;

        await VerifySG.VerifyIncrementalGeneratorAsync(source);
    }

    [Fact]
    public async Task NoGeneration_WhenNotAClass()
    {
        const string source =
            """
            using GraphQL;
            using GraphQL.Types;

            namespace Sample;

            public interface IMySchema
            {
            }
            """;

        await VerifySG.VerifyIncrementalGeneratorAsync(source);
    }
}
