using System.Text;
using GraphQL.Analyzers.Interceptors.Models;
using Microsoft.CodeAnalysis.Text;

namespace GraphQL.Analyzers.Interceptors;

/// <summary>
/// Generates interceptor source code from FieldInterceptorInfo records.
/// </summary>
internal static class FieldInterceptorSourceGenerator
{
    /// <summary>
    /// Generates the interceptor source code for a single Field method invocation.
    /// </summary>
    public static (string FileName, SourceText SourceText)? Generate(FieldInterceptorInfo info)
    {
        // Create a unique method name based on location
        var displayLocation = info.Location.GetDisplayLocation();
        var methodName = $"Field_{displayLocation}";
        var fileName = $"FieldInterceptors_{displayLocation}.g.cs";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        // Generate the InterceptsLocationAttribute in the same file (file-local)
        sb.AppendLine("namespace System.Runtime.CompilerServices");
        sb.AppendLine("{");
        sb.AppendLine("    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]");
        sb.AppendLine("    file sealed class InterceptsLocationAttribute(int version, string data) : global::System.Attribute;");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("namespace GraphQL.Analyzers.Interceptors");
        sb.AppendLine("{");
        sb.AppendLine("    internal static partial class FieldInterceptors");
        sb.AppendLine("    {");
        sb.AppendLine($"        {info.Location.GetInterceptsLocationAttributeSyntax()}");

        // Build method signature based on which parameters are present
        sb.Append($"        internal static global::GraphQL.Builders.FieldBuilder<{info.SourceTypeFullName}, {info.PropertyTypeFullName}> {methodName}<TProperty>(");
        sb.AppendLine();
        sb.AppendLine($"            this global::GraphQL.Types.ComplexGraphType<{info.SourceTypeFullName}> graphType,");

        // Conditionally add name parameter
        if (info.HasNameParameter)
        {
            sb.AppendLine($"            string name,");
        }

        sb.Append($"            global::System.Linq.Expressions.Expression<global::System.Func<{info.SourceTypeFullName}, {info.PropertyTypeFullName}>> expression");

        // Conditionally add nullable parameter
        if (info.HasNullableParameter)
        {
            sb.AppendLine(",");
            sb.Append($"            bool nullable");
        }

        // Conditionally add type parameter
        if (info.HasTypeParameter)
        {
            sb.AppendLine(",");
            sb.Append($"            global::System.Type type");
        }

        sb.AppendLine(")");
        sb.AppendLine("        {");

        // Build the call to CreateFieldFromExpression
        sb.AppendLine($"            return global::GraphQL.Utilities.FieldBuilderHelpers.CreateFieldFromExpression<{info.SourceTypeFullName}, {info.PropertyTypeFullName}>(");
        sb.AppendLine("                graphType,");

        // Pass name parameter or null
        if (info.HasNameParameter)
        {
            sb.AppendLine("                name,");
        }
        else
        {
            sb.AppendLine("                null,");
        }

        sb.AppendLine("                expression,");

        // Pass nullable parameter or null
        if (info.HasNullableParameter)
        {
            sb.AppendLine("                nullable: nullable,");
        }
        else
        {
            sb.AppendLine("                nullable: null,");
        }

        // Pass type parameter or null
        if (info.HasTypeParameter)
        {
            sb.AppendLine("                type: type,");
        }
        else
        {
            sb.AppendLine("                type: null,");
        }

        sb.AppendLine($"                resolve: context => context.Source!.{info.MemberName});");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return (fileName, SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
