using System.Text;
using GraphQL.Analyzers.Interceptors.Models;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace GraphQL.Analyzers.Interceptors;

/// <summary>
/// Generates interceptor source code from FieldInterceptorInfo records.
/// </summary>
internal static class FieldInterceptorSourceGenerator
{
    /// <summary>
    /// Generates the interceptor source code for a single Field method invocation.
    /// </summary>
    public static (string FileName, SourceText SourceText)? Generate(FieldInterceptorInfo info)
    {
        if (!info.IsValid || info.Location == null || info.SourceTypeFullName == null || info.PropertyTypeFullName == null || info.MemberName == null)
            return null;

        // Create a unique method name based on location
        var displayLocation = info.Location.GetDisplayLocation().Replace(":", "_").Replace("(", "_").Replace(")", "_").Replace(",", "_");
        var methodName = $"Field_{displayLocation}";
        var fileName = $"FieldInterceptors_{displayLocation}.g.cs";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        // Generate the InterceptsLocationAttribute in the same file (file-local)
        sb.AppendLine("namespace System.Runtime.CompilerServices");
        sb.AppendLine("{");
        sb.AppendLine("    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]");
        sb.AppendLine("    file sealed class InterceptsLocationAttribute(int version, string data) : global::System.Attribute;");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("namespace GraphQL.Analyzers.Interceptors");
        sb.AppendLine("{");
        sb.AppendLine("    internal static partial class FieldInterceptors");
        sb.AppendLine("    {");
        sb.AppendLine($"        {info.Location.GetInterceptsLocationAttributeSyntax()}");
        sb.AppendLine($"        internal static global::GraphQL.Builders.FieldBuilder<{info.SourceTypeFullName}, {info.PropertyTypeFullName}> {methodName}<TGraphType>(");
        sb.AppendLine($"            this global::GraphQL.Types.ComplexGraphType<{info.SourceTypeFullName}> graphType,");
        sb.AppendLine($"            string name,");
        sb.AppendLine($"            global::System.Linq.Expressions.Expression<global::System.Func<{info.SourceTypeFullName}, {info.PropertyTypeFullName}>> expression)");
        sb.AppendLine($"            where TGraphType : global::GraphQL.Types.ComplexGraphType<{info.SourceTypeFullName}>");
        sb.AppendLine("        {");
        sb.AppendLine($"            return global::GraphQL.Utilities.FieldBuilderHelpers.CreateFieldFromExpression<{info.SourceTypeFullName}, {info.PropertyTypeFullName}>(");
        sb.AppendLine("                graphType,");
        sb.AppendLine("                name,");
        sb.AppendLine("                expression,");
        sb.AppendLine("                nullable: null,");
        sb.AppendLine("                type: null,");
        sb.AppendLine($"                resolve: context => context.Source!.{info.MemberName});");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return (fileName, SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
