using System.Text;
using GraphQL.Analyzers.Interceptors.Models;
using GraphQL.Analyzers.SourceGenerators;
using Microsoft.CodeAnalysis.Text;

namespace GraphQL.Analyzers.Interceptors;

/// <summary>
/// Generates interceptor source code from ResolveDelegateInterceptorInfo records.
/// </summary>
internal static class ResolveDelegateInterceptorSourceGenerator
{
    /// <summary>
    /// Generates the interceptor source code for a single ResolveDelegate method invocation.
    /// </summary>
    public static (string FileName, SourceText SourceText)? Generate(ResolveDelegateInterceptorInfo info)
    {
        var displayLocation = info.Location.GetDisplayLocation();
        var methodName = $"ResolveDelegate_{displayLocation}";
        var fileName = $"ResolveDelegateInterceptors_{displayLocation}.g.cs";

        var sb = new SourceBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine();

        // Generate the InterceptsLocationAttribute in the same file (file-local)
        sb.AppendLine("namespace System.Runtime.CompilerServices");
        sb.AppendLine("{");
        using (sb.Indent())
        {
            sb.AppendLine("[global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]");
            sb.AppendLine("file sealed class InterceptsLocationAttribute(int version, string data) : global::System.Attribute;");
        }
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("namespace GraphQL.Analyzers.Interceptors");
        sb.AppendLine("{");
        using (sb.Indent())
        {
            sb.AppendLine("internal static partial class ResolveDelegateInterceptors");
            sb.AppendLine("{");
            using (sb.Indent())
            {
                sb.AppendLine($"{info.Location.GetInterceptsLocationAttributeSyntax()}");

                // Method signature: intercepts FieldBuilder<TSourceType, TReturnType>.ResolveDelegate(Delegate? resolve)
                sb.AppendLine($"internal static global::GraphQL.Builders.FieldBuilder<{info.SourceTypeFullName}, {info.ReturnTypeFullName}> {methodName}(");
                using (sb.Indent())
                {
                    sb.AppendLine($"this global::GraphQL.Builders.FieldBuilder<{info.SourceTypeFullName}, {info.ReturnTypeFullName}> fieldBuilder,");
                    sb.Append("global::System.Delegate? resolve");
                }
                sb.AppendLine(")");
                sb.AppendLine("{");
                using (sb.Indent())
                {
                    GenerateMethodBody(sb, info);
                }
                sb.AppendLine("}");
            }
            sb.AppendLine("}");
        }
        sb.AppendLine("}");

        return (fileName, SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void GenerateMethodBody(SourceBuilder sb, ResolveDelegateInterceptorInfo info)
    {
        // Handle null delegate case
        if (info.IsNullDelegate)
        {
            sb.AppendLine("return fieldBuilder.Resolve((global::GraphQL.Resolvers.IFieldResolver?)null);");
            return;
        }

        // Check if any parameters need BuildArgument (non-context parameters)
        bool hasNonContextParams = info.Parameters.Any(p => !p.IsContextParameter);

        // If there are non-context parameters, get the ParameterInfo array from the method
        // and call BuildArgument<T>(fieldType, parameters[i]) for each one
        if (hasNonContextParams)
        {
            sb.AppendLine("var fieldType = fieldBuilder.FieldType;");

            // Build the parameter type array for GetMethod disambiguation
            var paramTypeArgs = string.Join(", ", info.MethodParameterTypeNames.Select(t => $"typeof({t})"));
            sb.AppendLine($"var parameters = typeof({info.DeclaringTypeFullName}).GetMethod(nameof({info.DeclaringTypeFullName}.{info.MethodName}), [{paramTypeArgs}])!.GetParameters();");

            // For each non-context parameter, call BuildArgument<T>(fieldType, parameters[index])
            // Track a separate counter for param0, param1, etc.
            int buildArgCounter = 0;
            for (int i = 0; i < info.Parameters.Count; i++)
            {
                var param = info.Parameters[i];
                if (!param.IsContextParameter)
                {
                    sb.AppendLine($"var param{buildArgCounter} = global::GraphQL.Utilities.ResolveDelegateHelpers.BuildArgument<{param.FullyQualifiedTypeName}>(fieldType, parameters[{i}]);");
                    buildArgCounter++;
                }
            }
            sb.AppendLine();
        }

        if (!info.IsStatic)
        {
            // Capture the delegate target at interception time (not inside the lambda)
            sb.AppendLine($"var target = ({info.DeclaringTypeFullName})resolve!.Target!;");
        }

        sb.AppendLine($"return fieldBuilder.Resolve(new global::GraphQL.Resolvers.FuncFieldResolver<{info.ReturnTypeFullName}>(context =>");
        sb.AppendLine("{");
        using (sb.Indent())
        {
            // Resolve each parameter
            int buildArgIndex = 0;
            for (int i = 0; i < info.Parameters.Count; i++)
            {
                var param = info.Parameters[i];
                if (param.IsContextParameter)
                {
                    if (IsCancellationToken(param.FullyQualifiedTypeName))
                    {
                        sb.AppendLine($"var arg{i} = context.CancellationToken;");
                    }
                    else
                    {
                        // IResolveFieldContext or similar - pass context directly
                        sb.AppendLine($"var arg{i} = ({param.FullyQualifiedTypeName})context;");
                    }
                }
                else
                {
                    // Resolve via the pre-built BuildArgument resolver func
                    sb.AppendLine($"var arg{i} = param{buildArgIndex}(context);");
                    buildArgIndex++;
                }
            }

            var argList = string.Join(", ", Enumerable.Range(0, info.Parameters.Count).Select(i => $"arg{i}"));
            var callTarget = info.IsStatic ? info.DeclaringTypeFullName : "target";
            sb.AppendLine($"return {callTarget}.{info.MethodName}({argList});");
        }
        sb.AppendLine("}));");
    }

    private static bool IsCancellationToken(string fullyQualifiedTypeName)
        => fullyQualifiedTypeName == "global::System.Threading.CancellationToken" ||
           fullyQualifiedTypeName.EndsWith(".CancellationToken");
}
