// <auto-generated />
using DataLoaderGql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataLoaderGql.Migrations
{
    [DbContext(typeof(DealershipDbContext))]
    [Migration("20241122201609_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("DataLoaderGql.Types.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ModelYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SalespersonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SalespersonId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("DataLoaderGql.Types.Salesperson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Salespeople");
                });

            modelBuilder.Entity("DataLoaderGql.Types.Car", b =>
                {
                    b.HasOne("DataLoaderGql.Types.Salesperson", null)
                        .WithMany("AssignedCars")
                        .HasForeignKey("SalespersonId");
                });

            modelBuilder.Entity("DataLoaderGql.Types.Salesperson", b =>
                {
                    b.Navigation("AssignedCars");
                });
#pragma warning restore 612, 618
        }
    }
}
