using System.Text;
using GraphQL.Analyzers.SourceGenerators.Models;

namespace GraphQL.Analyzers.SourceGenerators.Generators;

/// <summary>
/// Generates input graph type code for AOT scenarios.
/// </summary>
public static class InputGraphTypeGenerator
{
    /// <summary>
    /// Generates the complete input graph type source code.
    /// </summary>
    /// <param name="namespace">The namespace for the generated class.</param>
    /// <param name="partialClassHierarchy">The hierarchy of partial classes.</param>
    /// <param name="inputGraphType">The input graph type data containing member information.</param>
    /// <returns>The generated source code as a string.</returns>
    public static string Generate(
        string? @namespace,
        ImmutableEquatableArray<PartialClassInfo> partialClassHierarchy,
        InputGraphTypeData? inputGraphType)
    {
        if (inputGraphType == null || partialClassHierarchy.Count == 0)
        {
            return string.Empty;
        }

        var sb = new StringBuilder();

        // Header
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        // Namespace
        if (!string.IsNullOrEmpty(@namespace))
        {
            sb.AppendLine($"namespace {@namespace};");
            sb.AppendLine();
        }

        // Class declaration
        GenerateClassDeclaration(sb, partialClassHierarchy, inputGraphType);

        return sb.ToString();
    }

    private static void GenerateClassDeclaration(
        StringBuilder sb,
        ImmutableEquatableArray<PartialClassInfo> partialClassHierarchy,
        InputGraphTypeData inputGraphType)
    {
        // Generate nested partial classes from outermost to innermost
        int indentLevel = 0;
        for (int i = 0; i < partialClassHierarchy.Count; i++)
        {
            var classInfo = partialClassHierarchy[i];
            var classAccessibility = classInfo.Accessibility switch
            {
                ClassAccessibility.Public => "public",
                ClassAccessibility.Private => "private",
                _ => "internal"
            };

            sb.Append(new string(' ', indentLevel * 4));
            sb.AppendLine($"{classAccessibility} partial class {classInfo.ClassName}");
            sb.Append(new string(' ', indentLevel * 4));
            sb.AppendLine("{");
            indentLevel++;
        }

        // Generate the inner auto-registering graph type class
        GenerateAutoRegisteringInputGraphType(sb, indentLevel, inputGraphType);

        // Close all class declarations
        for (int i = partialClassHierarchy.Count - 1; i >= 0; i--)
        {
            indentLevel--;
            sb.Append(new string(' ', indentLevel * 4));
            sb.AppendLine("}");
        }
    }

    private static void GenerateAutoRegisteringInputGraphType(
        StringBuilder sb,
        int indentLevel,
        InputGraphTypeData inputGraphType)
    {
        var indent = new string(' ', indentLevel * 4);
        var baseType = $"global::GraphQL.Types.Aot.AotAutoRegisteringInputObjectGraphType<{inputGraphType.FullyQualifiedClrTypeName}>";

        // Class declaration
        sb.AppendLine($"{indent}private class {inputGraphType.GraphTypeClassName} : {baseType}");
        sb.AppendLine($"{indent}{{");

        // Generate fields
        GenerateFields(sb, indentLevel + 1);

        // Generate constructor
        GenerateConstructor(sb, indentLevel + 1, inputGraphType);

        // Generate GetRegisteredMembers method
        GenerateGetRegisteredMembersMethod(sb, indentLevel + 1);

        // Generate ParseDictionary method
        GenerateParseDictionaryMethod(sb, indentLevel + 1, inputGraphType);

        // Generate IsValidDefault method
        GenerateIsValidDefaultMethod(sb, indentLevel + 1, inputGraphType);

        // Generate ToAST method
        GenerateToASTMethod(sb, indentLevel + 1, inputGraphType);

        sb.AppendLine($"{indent}}}");
    }

    private static void GenerateFields(
        StringBuilder sb,
        int indentLevel)
    {
        var indent = new string(' ', indentLevel * 4);

        sb.AppendLine($"{indent}private readonly global::System.Reflection.MemberInfo[] _members;");
        sb.AppendLine($"{indent}private readonly global::GraphQL.Types.FieldType[] _fields;");
        sb.AppendLine();
    }

    private static void GenerateConstructor(
        StringBuilder sb,
        int indentLevel,
        InputGraphTypeData inputGraphType)
    {
        var indent = new string(' ', indentLevel * 4);

        sb.AppendLine($"{indent}public {inputGraphType.GraphTypeClassName}()");
        sb.AppendLine($"{indent}{{");

        // Initialize _members array
        sb.AppendLine($"{indent}    _members = [");
        for (int i = 0; i < inputGraphType.Members.Count; i++)
        {
            var member = inputGraphType.Members[i];
            var declaringType = member.DeclaringTypeFullyQualifiedName ?? inputGraphType.FullyQualifiedClrTypeName;
            var comma = i < inputGraphType.Members.Count - 1 ? "," : "";
            sb.AppendLine($"{indent}        typeof({declaringType}).GetProperty(nameof({declaringType}.{member.MemberName}))!{comma}");
        }
        sb.AppendLine($"{indent}    ];");

        // Initialize _fields array
        sb.AppendLine($"{indent}    _fields = global::System.Linq.Enumerable.ToArray(ProvideFields());");

        // Add fields
        sb.AppendLine($"{indent}    foreach (var fieldType in _fields)");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        AddField(fieldType);");
        sb.AppendLine($"{indent}    }}");

        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
    }

    private static void GenerateGetRegisteredMembersMethod(
        StringBuilder sb,
        int indentLevel)
    {
        var indent = new string(' ', indentLevel * 4);

        sb.AppendLine($"{indent}protected override global::System.Collections.Generic.IEnumerable<global::System.Reflection.MemberInfo> GetRegisteredMembers() => _members;");
        sb.AppendLine();
    }

    private static void GenerateParseDictionaryMethod(
        StringBuilder sb,
        int indentLevel,
        InputGraphTypeData inputGraphType)
    {
        var indent = new string(' ', indentLevel * 4);

        sb.AppendLine($"{indent}public override object ParseDictionary(global::System.Collections.Generic.IDictionary<string, object?> value, global::GraphQL.IValueConverter valueConverter)");
        sb.AppendLine($"{indent}{{");

        // Check if we have constructor parameters
        if (inputGraphType.ConstructorParameters.Count > 0)
        {
            // Identify which members are not in constructor parameters
            var constructorMemberNames = new System.Collections.Generic.HashSet<string>(
                inputGraphType.ConstructorParameters.Select(p => p.MemberName));
            var nonConstructorMembers = new System.Collections.Generic.List<int>();

            for (int i = 0; i < inputGraphType.Members.Count; i++)
            {
                if (!constructorMemberNames.Contains(inputGraphType.Members[i].MemberName))
                {
                    nonConstructorMembers.Add(i);
                }
            }

            // Constructor with parameters
            sb.AppendLine($"{indent}    return new {inputGraphType.FullyQualifiedClrTypeName}(");

            for (int i = 0; i < inputGraphType.ConstructorParameters.Count; i++)
            {
                var param = inputGraphType.ConstructorParameters[i];
                var memberIndex = GetMemberIndex(inputGraphType, param.MemberName);
                var member = inputGraphType.Members[memberIndex];
                var comma = i < inputGraphType.ConstructorParameters.Count - 1 ? "," : "";
                sb.AppendLine($"{indent}        ParseField<{member.FullyQualifiedTypeName}>(_fields[{memberIndex}]){comma}");
            }
            sb.Append($"{indent}    )");

            // Add object initializer for non-constructor members if any
            if (nonConstructorMembers.Count > 0)
            {
                sb.AppendLine();
                sb.AppendLine($"{indent}    {{");

                for (int i = 0; i < nonConstructorMembers.Count; i++)
                {
                    var memberIndex = nonConstructorMembers[i];
                    var member = inputGraphType.Members[memberIndex];
                    var comma = i < nonConstructorMembers.Count - 1 ? "," : "";
                    sb.AppendLine($"{indent}        {member.MemberName} = ParseField<{member.FullyQualifiedTypeName}>(_fields[{memberIndex}]){comma}");
                }

                sb.AppendLine($"{indent}    }};");
            }
            else
            {
                sb.AppendLine(";");
            }
        }
        else
        {
            // Object initializer
            sb.AppendLine($"{indent}    return new {inputGraphType.FullyQualifiedClrTypeName}");
            sb.AppendLine($"{indent}    {{");

            for (int i = 0; i < inputGraphType.Members.Count; i++)
            {
                var member = inputGraphType.Members[i];
                var comma = i < inputGraphType.Members.Count - 1 ? "," : "";
                sb.AppendLine($"{indent}        {member.MemberName} = ParseField<{member.FullyQualifiedTypeName}>(_fields[{i}]){comma}");
            }

            sb.AppendLine($"{indent}    }};");
        }

        sb.AppendLine();
        sb.AppendLine($"{indent}    TFieldType ParseField<TFieldType>(global::GraphQL.Types.FieldType fieldType)");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        if (value.TryGetValue(fieldType.Name, out var fieldValue))");
        sb.AppendLine($"{indent}        {{");
        sb.AppendLine($"{indent}            return (TFieldType)global::GraphQL.ValueConverterExtensions.GetPropertyValue(valueConverter, fieldValue, typeof(TFieldType), fieldType.ResolvedType!)!;");
        sb.AppendLine($"{indent}        }}");
        sb.AppendLine($"{indent}        return default!;");
        sb.AppendLine($"{indent}    }}");

        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
    }

    private static void GenerateIsValidDefaultMethod(
        StringBuilder sb,
        int indentLevel,
        InputGraphTypeData inputGraphType)
    {
        var indent = new string(' ', indentLevel * 4);

        sb.AppendLine($"{indent}public override bool IsValidDefault(object value)");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    if (value is not {inputGraphType.FullyQualifiedClrTypeName} obj)");
        sb.AppendLine($"{indent}        return false;");
        sb.AppendLine();

        for (int i = 0; i < inputGraphType.Members.Count; i++)
        {
            var member = inputGraphType.Members[i];
            sb.AppendLine($"{indent}    if (global::GraphQL.GraphQLExtensions.IsValidDefault(_fields[{i}].ResolvedType!, obj.{member.MemberName}))");
            sb.AppendLine($"{indent}        return false;");
        }

        sb.AppendLine();
        sb.AppendLine($"{indent}    return true;");
        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
    }

    private static void GenerateToASTMethod(
        StringBuilder sb,
        int indentLevel,
        InputGraphTypeData inputGraphType)
    {
        var indent = new string(' ', indentLevel * 4);

        sb.AppendLine($"{indent}public override global::GraphQLParser.AST.GraphQLValue ToAST(object? value)");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    if (value == null)");
        sb.AppendLine($"{indent}        return new global::GraphQLParser.AST.GraphQLNullValue();");
        sb.AppendLine();
        sb.AppendLine($"{indent}    if (value is not {inputGraphType.FullyQualifiedClrTypeName} obj)");
        sb.AppendLine($"{indent}        return null!; //allowed return to indicate failure");
        sb.AppendLine();
        sb.AppendLine($"{indent}    var objectValue = new global::GraphQLParser.AST.GraphQLObjectValue");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        Fields = new(_fields.Length)");
        sb.AppendLine($"{indent}    }};");
        sb.AppendLine();

        for (int i = 0; i < inputGraphType.Members.Count; i++)
        {
            var member = inputGraphType.Members[i];
            sb.AppendLine($"{indent}    ProcessField(_fields[{i}], obj.{member.MemberName});");
        }

        sb.AppendLine();
        sb.AppendLine($"{indent}    return objectValue;");
        sb.AppendLine();
        sb.AppendLine($"{indent}    void ProcessField(global::GraphQL.Types.FieldType fieldType, object? fieldValue)");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        var ast = global::GraphQL.GraphQLExtensions.ToAST(fieldType.ResolvedType!, fieldValue)");
        sb.AppendLine($"{indent}            ?? throw new global::System.InvalidOperationException($\"Could not convert value in {inputGraphType.FullyQualifiedClrTypeName}.{{fieldType.Name}} to AST\");");
        sb.AppendLine($"{indent}        if (ast is not global::GraphQLParser.AST.GraphQLNullValue || fieldType.DefaultValue != null)");
        sb.AppendLine($"{indent}            objectValue.Fields.Add(new(new(fieldType.Name), ast));");
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine($"{indent}}}");
    }

    private static int GetMemberIndex(InputGraphTypeData inputGraphType, string memberName)
    {
        for (int i = 0; i < inputGraphType.Members.Count; i++)
        {
            if (inputGraphType.Members[i].MemberName == memberName)
                return i;
        }
        return -1;
    }
}
