using GraphQL.Analyzers.SourceGenerators.Models;

namespace GraphQL.Analyzers.SourceGenerators.Generators;

/// <summary>
/// Generates input graph type code for AOT scenarios.
/// </summary>
public static class InputGraphTypeGenerator
{
    /// <summary>
    /// Generates the complete input graph type source code.
    /// </summary>
    /// <param name="namespace">The namespace for the generated class.</param>
    /// <param name="partialClassHierarchy">The hierarchy of partial classes.</param>
    /// <param name="inputGraphType">The input graph type data containing member information.</param>
    /// <returns>The generated source code as a string.</returns>
    public static string Generate(
        string? @namespace,
        ImmutableEquatableArray<PartialClassInfo> partialClassHierarchy,
        InputGraphTypeData? inputGraphType)
    {
        if (inputGraphType == null || partialClassHierarchy.Count == 0)
        {
            return string.Empty;
        }

        var sb = new SourceBuilder();

        // Header
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        // Namespace
        if (!string.IsNullOrEmpty(@namespace))
        {
            sb.AppendLine($"namespace {@namespace};");
            sb.AppendLine();
        }

        // Class declaration
        GenerateClassDeclaration(sb, partialClassHierarchy, inputGraphType);

        return sb.ToString();
    }

    private static void GenerateClassDeclaration(
        SourceBuilder sb,
        ImmutableEquatableArray<PartialClassInfo> partialClassHierarchy,
        InputGraphTypeData inputGraphType)
    {
        // Generate nested partial classes from outermost to innermost
        for (int i = 0; i < partialClassHierarchy.Count; i++)
        {
            var classInfo = partialClassHierarchy[i];
            var classAccessibility = classInfo.Accessibility switch
            {
                ClassAccessibility.Public => "public",
                ClassAccessibility.Private => "private",
                _ => "internal"
            };

            sb.AppendLine($"{classAccessibility} partial class {classInfo.ClassName}");
            sb.AppendLine("{");
            sb.Indentation++;
        }

        // Generate the inner auto-registering graph type class
        GenerateAutoRegisteringInputGraphType(sb, inputGraphType);

        // Close all class declarations
        for (int i = partialClassHierarchy.Count - 1; i >= 0; i--)
        {
            sb.Indentation--; // Un-indent
            sb.AppendLine("}");
        }
    }

    private static void GenerateAutoRegisteringInputGraphType(
        SourceBuilder sb,
        InputGraphTypeData inputGraphType)
    {
        var baseType = $"global::GraphQL.Types.Aot.AotAutoRegisteringInputObjectGraphType<{inputGraphType.FullyQualifiedClrTypeName}>";

        // Class declaration
        sb.AppendLine($"private class {inputGraphType.GraphTypeClassName} : {baseType}");
        sb.AppendLine("{");

        using (sb.Indent())
        {
            // Generate fields
            GenerateFields(sb, inputGraphType);

            // Generate constructors
            GenerateStaticConstructor(sb, inputGraphType);
            GeneratePublicConstructor(sb, inputGraphType);
            GeneratePrivateConstructor(sb, inputGraphType);

            // Generate GetRegisteredMembers method
            GenerateGetRegisteredMembersMethod(sb);

            // Generate ParseDictionary method
            GenerateParseDictionaryMethod(sb, inputGraphType);

            // Generate IsValidDefault method
            GenerateIsValidDefaultMethod(sb, inputGraphType);

            // Generate ToAST method
            GenerateToASTMethod(sb, inputGraphType);
        }

        sb.AppendLine("}");
    }

    private static void GenerateFields(SourceBuilder sb, InputGraphTypeData inputGraphType)
    {
        sb.AppendLine($"private static {inputGraphType.GraphTypeClassName}? _cache;");
        sb.AppendLine("private static readonly global::System.Reflection.MemberInfo[] _members;");
        sb.AppendLine("private readonly global::GraphQL.Types.FieldType[] _fields;");
        sb.AppendLine();
    }

    private static void GenerateStaticConstructor(
        SourceBuilder sb,
        InputGraphTypeData inputGraphType)
    {
        sb.AppendLine($"static {inputGraphType.GraphTypeClassName}()");
        sb.AppendLine("{");
        using (sb.Indent())
        {
            // Initialize _members array
            sb.AppendLine("_members = [");
            using (sb.Indent())
            {
                for (int i = 0; i < inputGraphType.Members.Count; i++)
                {
                    var member = inputGraphType.Members[i];
                    var declaringType = member.DeclaringTypeFullyQualifiedName ?? inputGraphType.FullyQualifiedClrTypeName;
                    var comma = i < inputGraphType.Members.Count - 1 ? "," : "";
                    sb.AppendLine($"typeof({declaringType}).GetProperty(nameof({declaringType}.{member.MemberName}))!{comma}");
                }
            }
            sb.AppendLine("];");
        }
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void GeneratePublicConstructor(
        SourceBuilder sb,
        InputGraphTypeData inputGraphType)
    {
        sb.AppendLine($"public {inputGraphType.GraphTypeClassName}() : this(_cache)");
        sb.AppendLine("{");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void GeneratePrivateConstructor(
        SourceBuilder sb,
        InputGraphTypeData inputGraphType)
    {
        sb.AppendLine($"private {inputGraphType.GraphTypeClassName}({inputGraphType.GraphTypeClassName}? cloneFrom) : base(cloneFrom)");
        sb.AppendLine("{");

        using (sb.Indent())
        {
            // Check cache first
            sb.AppendLine("if (cloneFrom != null)");
            sb.AppendLine("{");
            using (sb.Indent())
            {
                sb.AppendLine("_fields = global::System.Linq.Enumerable.ToArray(cloneFrom.Fields);");
                sb.AppendLine("return;");
            }
            sb.AppendLine("}");
            sb.AppendLine();

            // Initialize _fields array
            sb.AppendLine("_fields = global::System.Linq.Enumerable.ToArray(ProvideFields());");

            // Add fields
            sb.AppendLine("foreach (var fieldType in _fields)");
            sb.AppendLine("{");
            using (sb.Indent())
            {
                sb.AppendLine("AddField(fieldType);");
            }
            sb.AppendLine("}");
            sb.AppendLine();

            // Set cache if enabled
            sb.AppendLine("if (global::GraphQL.GlobalSwitches.EnableReflectionCaching)");
            sb.AppendLine("{");
            using (sb.Indent())
            {
                sb.AppendLine($"_cache = new {inputGraphType.GraphTypeClassName}(this);");
            }
            sb.AppendLine("}");
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void GenerateGetRegisteredMembersMethod(SourceBuilder sb)
    {
        sb.AppendLine("protected override global::System.Collections.Generic.IEnumerable<global::System.Reflection.MemberInfo> GetRegisteredMembers() => _members;");
        sb.AppendLine();
    }

    private static void GenerateParseDictionaryMethod(
        SourceBuilder sb,
        InputGraphTypeData inputGraphType)
    {
        sb.AppendLine("public override object ParseDictionary(global::System.Collections.Generic.IDictionary<string, object?> value, global::GraphQL.IValueConverter valueConverter)");
        sb.AppendLine("{");

        using (sb.Indent())
        {
            // Check if we have constructor parameters
            if (inputGraphType.ConstructorParameters.Count > 0)
            {
                // Identify which members are not in constructor parameters
                var constructorMemberNames = new System.Collections.Generic.HashSet<string>(
                    inputGraphType.ConstructorParameters.Select(p => p.MemberName));
                var nonConstructorMembers = new System.Collections.Generic.List<int>();

                for (int i = 0; i < inputGraphType.Members.Count; i++)
                {
                    if (!constructorMemberNames.Contains(inputGraphType.Members[i].MemberName))
                    {
                        nonConstructorMembers.Add(i);
                    }
                }

                // Constructor with parameters
                sb.AppendLine($"return new {inputGraphType.FullyQualifiedClrTypeName}(");

                using (sb.Indent())
                {
                    for (int i = 0; i < inputGraphType.ConstructorParameters.Count; i++)
                    {
                        var param = inputGraphType.ConstructorParameters[i];
                        var memberIndex = GetMemberIndex(inputGraphType, param.MemberName);
                        var member = inputGraphType.Members[memberIndex];
                        var comma = i < inputGraphType.ConstructorParameters.Count - 1 ? "," : "";
                        sb.AppendLine($"ParseField<{member.FullyQualifiedTypeName}>(_fields[{memberIndex}]){comma}");
                    }
                }

                // Add object initializer for non-constructor members if any
                if (nonConstructorMembers.Count > 0)
                {
                    sb.Append(")");
                    sb.AppendLine();
                    sb.AppendLine("{");

                    using (sb.Indent())
                    {
                        for (int i = 0; i < nonConstructorMembers.Count; i++)
                        {
                            var memberIndex = nonConstructorMembers[i];
                            var member = inputGraphType.Members[memberIndex];
                            var comma = i < nonConstructorMembers.Count - 1 ? "," : "";
                            sb.AppendLine($"{member.MemberName} = ParseField<{member.FullyQualifiedTypeName}>(_fields[{memberIndex}]){comma}");
                        }
                    }

                    sb.AppendLine("};");
                }
                else
                {
                    sb.Append(");");
                    sb.AppendLine();
                }
            }
            else
            {
                // Object initializer
                sb.AppendLine($"return new {inputGraphType.FullyQualifiedClrTypeName}");
                sb.AppendLine("{");

                using (sb.Indent())
                {
                    for (int i = 0; i < inputGraphType.Members.Count; i++)
                    {
                        var member = inputGraphType.Members[i];
                        var comma = i < inputGraphType.Members.Count - 1 ? "," : "";
                        sb.AppendLine($"{member.MemberName} = ParseField<{member.FullyQualifiedTypeName}>(_fields[{i}]){comma}");
                    }
                }

                sb.AppendLine("};");
            }

            sb.AppendLine();
            sb.AppendLine("TFieldType ParseField<TFieldType>(global::GraphQL.Types.FieldType fieldType)");
            sb.AppendLine("{");
            using (sb.Indent())
            {
                sb.AppendLine("if (value.TryGetValue(fieldType.Name, out var fieldValue))");
                sb.AppendLine("{");
                using (sb.Indent())
                {
                    sb.AppendLine("return (TFieldType)global::GraphQL.ValueConverterExtensions.GetPropertyValue(valueConverter, fieldValue, typeof(TFieldType), fieldType.ResolvedType!)!;");
                }
                sb.AppendLine("}");
                sb.AppendLine("return default!;");
            }
            sb.AppendLine("}");
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void GenerateIsValidDefaultMethod(
        SourceBuilder sb,
        InputGraphTypeData inputGraphType)
    {
        sb.AppendLine("public override bool IsValidDefault(object value)");
        sb.AppendLine("{");

        using (sb.Indent())
        {
            sb.AppendLine($"if (value is not {inputGraphType.FullyQualifiedClrTypeName} obj)");
            using (sb.Indent())
            {
                sb.AppendLine("return false;");
            }
            sb.AppendLine();

            for (int i = 0; i < inputGraphType.Members.Count; i++)
            {
                var member = inputGraphType.Members[i];
                sb.AppendLine($"if (global::GraphQL.GraphQLExtensions.IsValidDefault(_fields[{i}].ResolvedType!, obj.{member.MemberName}))");
                using (sb.Indent())
                {
                    sb.AppendLine("return false;");
                }
            }

            sb.AppendLine();
            sb.AppendLine("return true;");
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void GenerateToASTMethod(
        SourceBuilder sb,
        InputGraphTypeData inputGraphType)
    {
        sb.AppendLine("public override global::GraphQLParser.AST.GraphQLValue ToAST(object? value)");
        sb.AppendLine("{");

        using (sb.Indent())
        {
            sb.AppendLine("if (value == null)");
            using (sb.Indent())
            {
                sb.AppendLine("return new global::GraphQLParser.AST.GraphQLNullValue();");
            }
            sb.AppendLine();

            sb.AppendLine($"if (value is not {inputGraphType.FullyQualifiedClrTypeName} obj)");
            using (sb.Indent())
            {
                sb.AppendLine("return null!; //allowed return to indicate failure");
            }
            sb.AppendLine();

            sb.AppendLine("var objectValue = new global::GraphQLParser.AST.GraphQLObjectValue");
            sb.AppendLine("{");
            using (sb.Indent())
            {
                sb.AppendLine("Fields = new(_fields.Length)");
            }
            sb.AppendLine("};");
            sb.AppendLine();

            for (int i = 0; i < inputGraphType.Members.Count; i++)
            {
                var member = inputGraphType.Members[i];
                sb.AppendLine($"ProcessField(_fields[{i}], obj.{member.MemberName});");
            }

            sb.AppendLine();
            sb.AppendLine("return objectValue;");
            sb.AppendLine();

            sb.AppendLine("void ProcessField(global::GraphQL.Types.FieldType fieldType, object? fieldValue)");
            sb.AppendLine("{");
            using (sb.Indent())
            {
                sb.AppendLine($"var ast = global::GraphQL.GraphQLExtensions.ToAST(fieldType.ResolvedType!, fieldValue)");
                using (sb.Indent())
                {
                    sb.AppendLine($"?? throw new global::System.InvalidOperationException($\"Could not convert value in {inputGraphType.FullyQualifiedClrTypeName}.{{fieldType.Name}} to AST\");");
                }
                sb.AppendLine("if (ast is not global::GraphQLParser.AST.GraphQLNullValue || fieldType.DefaultValue != null)");
                using (sb.Indent())
                {
                    sb.AppendLine("objectValue.Fields.Add(new(new(fieldType.Name), ast));");
                }
            }
            sb.AppendLine("}");
        }

        sb.AppendLine("}");
    }

    private static int GetMemberIndex(InputGraphTypeData inputGraphType, string memberName)
    {
        for (int i = 0; i < inputGraphType.Members.Count; i++)
        {
            if (inputGraphType.Members[i].MemberName == memberName)
                return i;
        }
        return -1;
    }
}
