using GraphQL.Analyzers.SourceGenerators.Models;

namespace GraphQL.Analyzers.SourceGenerators.Generators;

/// <summary>
/// Generates output graph type (object/interface) code for AOT scenarios.
/// </summary>
public static class OutputGraphTypeGenerator
{
    /// <summary>
    /// Generates the complete output graph type source code.
    /// </summary>
    /// <param name="namespace">The namespace for the generated class.</param>
    /// <param name="partialClassHierarchy">The hierarchy of partial classes.</param>
    /// <param name="outputGraphType">The output graph type data containing field and member information.</param>
    /// <returns>The generated source code as a string.</returns>
    public static string Generate(
        string? @namespace,
        ImmutableEquatableArray<PartialClassInfo> partialClassHierarchy,
        OutputGraphTypeData? outputGraphType)
    {
        if (outputGraphType == null || partialClassHierarchy.Count == 0)
        {
            return string.Empty;
        }

        var sb = new SourceBuilder();

        // Header
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        // Namespace
        if (!string.IsNullOrEmpty(@namespace))
        {
            sb.AppendLine($"namespace {@namespace};");
            sb.AppendLine();
        }

        // Class declaration
        GenerateClassDeclaration(sb, partialClassHierarchy, outputGraphType);

        return sb.ToString();
    }

    private static void GenerateClassDeclaration(
        SourceBuilder sb,
        ImmutableEquatableArray<PartialClassInfo> partialClassHierarchy,
        OutputGraphTypeData outputGraphType)
    {
        // Generate nested partial classes from outermost to innermost
        for (int i = 0; i < partialClassHierarchy.Count; i++)
        {
            var classInfo = partialClassHierarchy[i];
            var classAccessibility = classInfo.Accessibility switch
            {
                ClassAccessibility.Public => "public",
                ClassAccessibility.Private => "private",
                _ => "internal"
            };

            sb.AppendLine($"{classAccessibility} partial class {classInfo.ClassName}");
            sb.AppendLine("{");
            sb.Indentation++;
        }

        // Generate the inner auto-registering graph type class
        GenerateAutoRegisteringGraphType(sb, outputGraphType);

        // Close all class declarations
        for (int i = partialClassHierarchy.Count - 1; i >= 0; i--)
        {
            sb.Indentation--;
            sb.AppendLine("}");
        }
    }

    private static void GenerateAutoRegisteringGraphType(
        SourceBuilder sb,
        OutputGraphTypeData outputGraphType)
    {
        var baseType = outputGraphType.IsInterface
            ? $"global::GraphQL.Types.Aot.AotAutoRegisteringInterfaceGraphType<{outputGraphType.FullyQualifiedClrTypeName}>"
            : $"global::GraphQL.Types.Aot.AotAutoRegisteringObjectGraphType<{outputGraphType.FullyQualifiedClrTypeName}>";

        // Class declaration
        sb.AppendLine($"private class {outputGraphType.GraphTypeClassName} : {baseType}");
        sb.AppendLine("{");

        using (sb.Indent())
        {
            // Generate fields
            GenerateFields(sb, outputGraphType);

            // Generate constructors
            GeneratePublicConstructor(sb, outputGraphType);
            GeneratePrivateConstructor(sb, outputGraphType);

            // Generate GetRegisteredMembers method
            GenerateGetRegisteredMembersMethod(sb);

            // Generate BuildFieldType method
            GenerateBuildFieldTypeMethod(sb, outputGraphType);

            // Generate GetMemberInstance override if needed
            GenerateGetMemberInstanceOverride(sb, outputGraphType);

            // Generate ConstructField methods for object types
            GenerateConstructFieldMethods(sb, outputGraphType);
        }

        sb.AppendLine("}");
    }

    private static void GenerateFields(
        SourceBuilder sb,
        OutputGraphTypeData outputGraphType)
    {
        var actionType = outputGraphType.IsInterface
            ? "global::System.Action<global::GraphQL.Types.FieldType, global::System.Reflection.MemberInfo>?"
            : "global::System.Action<global::GraphQL.Types.FieldType, global::System.Reflection.MemberInfo>";

        sb.AppendLine($"private static {outputGraphType.GraphTypeClassName}? _cache;");
        sb.AppendLine($"private readonly global::System.Collections.Generic.Dictionary<global::System.Reflection.MemberInfo, {actionType}> _members = null!;");

        // Add _getMemberInstance field if needed
        if (outputGraphType.InstanceSource != InstanceSource.ContextSource)
        {
            sb.AppendLine($"private readonly global::System.Func<global::GraphQL.IResolveFieldContext, {outputGraphType.FullyQualifiedClrTypeName}> _getMemberInstance = null!;");
        }
        sb.AppendLine();
    }

    private static void GeneratePublicConstructor(
        SourceBuilder sb,
        OutputGraphTypeData outputGraphType)
    {
        sb.AppendLine($"public {outputGraphType.GraphTypeClassName}() : this(_cache)");
        sb.AppendLine("{");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void GeneratePrivateConstructor(
        SourceBuilder sb,
        OutputGraphTypeData outputGraphType)
    {
        sb.AppendLine($"private {outputGraphType.GraphTypeClassName}({outputGraphType.GraphTypeClassName}? cloneFrom) : base(cloneFrom)");
        sb.AppendLine("{");

        using (sb.Indent())
        {
            // Check cache first
            sb.AppendLine("if (cloneFrom != null)");
            sb.AppendLine("{");
            using (sb.Indent())
            {
                sb.AppendLine("return;");
            }
            sb.AppendLine("}");
            sb.AppendLine();

            // Initialize _getMemberInstance for object types only, but not for ContextSource
            if (!outputGraphType.IsInterface && outputGraphType.InstanceSource != InstanceSource.ContextSource)
            {
                GenerateGetMemberInstanceInitialization(sb, outputGraphType);
                sb.AppendLine();
            }

            // Initialize _members dictionary
            sb.AppendLine("_members = new()");
            sb.AppendLine("{");

            using (sb.Indent())
            {
                for (int i = 0; i < outputGraphType.SelectedMembers.Count; i++)
                {
                    GenerateMemberDictionaryEntry(sb, i, outputGraphType.SelectedMembers[i], outputGraphType);
                }
            }

            sb.AppendLine("};");

            // Add fields
            sb.AppendLine("foreach (var fieldType in ProvideFields())");
            sb.AppendLine("{");
            using (sb.Indent())
            {
                sb.AppendLine("AddField(fieldType);");
            }
            sb.AppendLine("}");
            sb.AppendLine();

            // Set cache if enabled
            sb.AppendLine("if (global::GraphQL.GlobalSwitches.EnableReflectionCaching)");
            sb.AppendLine("{");
            using (sb.Indent())
            {
                sb.AppendLine($"_cache = new {outputGraphType.GraphTypeClassName}(this);");
            }
            sb.AppendLine("}");
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void GenerateGetMemberInstanceInitialization(
        SourceBuilder sb,
        OutputGraphTypeData outputGraphType)
    {
        switch (outputGraphType.InstanceSource)
        {
            case InstanceSource.GetRequiredService:
                sb.AppendLine($"_getMemberInstance = BuildConstructorParameter<{outputGraphType.FullyQualifiedClrTypeName}>();");
                break;

            case InstanceSource.NewInstance:
                GenerateNewInstanceInitialization(sb, outputGraphType);
                break;

            case InstanceSource.GetServiceOrCreateInstance:
                GenerateGetServiceOrCreateInstanceInitialization(sb, outputGraphType);
                break;
        }
    }

    private static void GenerateNewInstanceInitialization(
        SourceBuilder sb,
        OutputGraphTypeData outputGraphType)
    {
        var constructorData = outputGraphType.ConstructorData;

        if (constructorData == null || (constructorData.Parameters.Count == 0 && constructorData.RequiredProperties.Count == 0))
        {
            // No parameters, simple constructor
            sb.AppendLine($"_getMemberInstance = context => new {outputGraphType.FullyQualifiedClrTypeName}();");
            return;
        }

        // Generate parameter builders
        for (int i = 0; i < constructorData.Parameters.Count; i++)
        {
            var param = constructorData.Parameters[i];
            if (param.FullyQualifiedTypeName != null)
            {
                sb.AppendLine($"var ctorParam{i} = BuildConstructorParameter<{param.FullyQualifiedTypeName}>();");
            }
        }

        // Generate required property builders
        for (int i = 0; i < constructorData.RequiredProperties.Count; i++)
        {
            var prop = constructorData.RequiredProperties[i];
            sb.AppendLine($"var reqProp{i} = BuildConstructorParameter<{prop.FullyQualifiedTypeName}>();");
        }

        // Generate lambda
        sb.AppendLine($"_getMemberInstance = context => new {outputGraphType.FullyQualifiedClrTypeName}(");

        using (sb.Indent())
        {
            // Constructor parameters
            for (int i = 0; i < constructorData.Parameters.Count; i++)
            {
                var comma = i < constructorData.Parameters.Count - 1 ? "," : "";
                if (constructorData.Parameters[i].FullyQualifiedTypeName != null)
                {
                    sb.AppendLine($"ctorParam{i}(context){comma}");
                }
            }
        }

        if (constructorData.RequiredProperties.Count > 0)
        {
            sb.Append(")");
            sb.AppendLine();
            sb.AppendLine("{");

            using (sb.Indent())
            {
                for (int i = 0; i < constructorData.RequiredProperties.Count; i++)
                {
                    var prop = constructorData.RequiredProperties[i];
                    var comma = i < constructorData.RequiredProperties.Count - 1 ? "," : "";
                    sb.AppendLine($"{prop.Name} = reqProp{i}(context){comma}");
                }
            }

            sb.AppendLine("};");
        }
        else
        {
            sb.Append(");");
            sb.AppendLine();
        }
    }

    private static void GenerateGetServiceOrCreateInstanceInitialization(
        SourceBuilder sb,
        OutputGraphTypeData outputGraphType)
    {
        var constructorData = outputGraphType.ConstructorData;

        // Generate parameter builders for constructor
        if (constructorData != null)
        {
            for (int i = 0; i < constructorData.Parameters.Count; i++)
            {
                var param = constructorData.Parameters[i];
                if (param.FullyQualifiedTypeName != null)
                {
                    sb.AppendLine($"var ctorParam{i} = BuildConstructorParameter<{param.FullyQualifiedTypeName}>();");
                }
            }

            for (int i = 0; i < constructorData.RequiredProperties.Count; i++)
            {
                var prop = constructorData.RequiredProperties[i];
                sb.AppendLine($"var reqProp{i} = BuildConstructorParameter<{prop.FullyQualifiedTypeName}>();");
            }
        }

        // Generate lambda that tries service first, then creates
        sb.AppendLine("_getMemberInstance = context =>");
        sb.AppendLine("{");

        using (sb.Indent())
        {
            sb.AppendLine($"var obj = ({outputGraphType.FullyQualifiedClrTypeName}?)context.RequestServices?.GetService(typeof({outputGraphType.FullyQualifiedClrTypeName}));");
            sb.AppendLine("if (obj != null)");
            using (sb.Indent())
            {
                sb.AppendLine("return obj;");
            }

            // Generate new instance creation
            if (constructorData == null || (constructorData.Parameters.Count == 0 && constructorData.RequiredProperties.Count == 0))
            {
                sb.AppendLine($"return new {outputGraphType.FullyQualifiedClrTypeName}();");
            }
            else
            {
                sb.AppendLine($"return new {outputGraphType.FullyQualifiedClrTypeName}(");

                using (sb.Indent())
                {
                    for (int i = 0; i < constructorData.Parameters.Count; i++)
                    {
                        var comma = i < constructorData.Parameters.Count - 1 ? "," : "";
                        if (constructorData.Parameters[i].FullyQualifiedTypeName != null)
                        {
                            sb.AppendLine($"ctorParam{i}(context){comma}");
                        }
                    }
                }

                if (constructorData.RequiredProperties.Count > 0)
                {
                    sb.Append(")");
                    sb.AppendLine();
                    sb.AppendLine("{");

                    using (sb.Indent())
                    {
                        for (int i = 0; i < constructorData.RequiredProperties.Count; i++)
                        {
                            var prop = constructorData.RequiredProperties[i];
                            var comma = i < constructorData.RequiredProperties.Count - 1 ? "," : "";
                            sb.AppendLine($"{prop.Name} = reqProp{i}(context){comma}");
                        }
                    }

                    sb.AppendLine("};");
                }
                else
                {
                    sb.Append(");");
                    sb.AppendLine();
                }
            }
        }

        sb.AppendLine("};");
    }

    private static void GenerateMemberDictionaryEntry(
        SourceBuilder sb,
        int memberIndex,
        OutputMemberData member,
        OutputGraphTypeData outputGraphType)
    {
        var declaringType = member.DeclaringTypeFullyQualifiedName ?? outputGraphType.FullyQualifiedClrTypeName;

        string memberAccessExpression;
        if (member.MemberKind == MemberKind.Method)
        {
            // For methods, include parameter types - all fully qualified
            var paramTypes = string.Join(", ", member.MethodParameters.Select(p => $"typeof({p.FullyQualifiedTypeName})"));
            memberAccessExpression = $"typeof({declaringType}).GetMethod(nameof({declaringType}.{member.MemberName}), [{paramTypes}])!";
        }
        else
        {
            // For properties and fields - all fully qualified
            var memberTypeString = member.MemberKind == MemberKind.Property ? "GetProperty" : "GetField";
            memberAccessExpression = $"typeof({declaringType}).{memberTypeString}(nameof({declaringType}.{member.MemberName}))!";
        }

        var actionValue = outputGraphType.IsInterface && !member.IsStatic ? "null" : $"ConstructField{memberIndex}_{member.MemberName}";

        sb.AppendLine($"{{ {memberAccessExpression}, {actionValue} }},");
    }

    private static void GenerateGetRegisteredMembersMethod(SourceBuilder sb)
    {
        sb.AppendLine("protected override global::System.Collections.Generic.IEnumerable<global::System.Reflection.MemberInfo> GetRegisteredMembers() => _members.Keys;");
    }

    private static void GenerateBuildFieldTypeMethod(
        SourceBuilder sb,
        OutputGraphTypeData outputGraphType)
    {
        sb.AppendLine("protected override void BuildFieldType(global::GraphQL.Types.FieldType fieldType, global::System.Reflection.MemberInfo memberInfo)");
        sb.AppendLine("{");

        using (sb.Indent())
        {
            if (outputGraphType.IsInterface)
            {
                sb.AppendLine("_members[memberInfo]?.Invoke(fieldType, memberInfo);");
                sb.AppendLine("if (!fieldType.IsPrivate)");
                sb.AppendLine("{");
                using (sb.Indent())
                {
                    sb.AppendLine("fieldType.Resolver = null;");
                    sb.AppendLine("fieldType.StreamResolver = null;");
                }
                sb.AppendLine("}");
            }
            else
            {
                sb.AppendLine("_members[memberInfo](fieldType, memberInfo);");
            }
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void GenerateGetMemberInstanceOverride(
        SourceBuilder sb,
        OutputGraphTypeData outputGraphType)
    {
        // Only generate for object types
        if (!outputGraphType.IsInterface)
        {
            if (outputGraphType.InstanceSource == InstanceSource.ContextSource)
            {
                return; // No override needed for ContextSource
            }

            sb.AppendLine($"protected override {outputGraphType.FullyQualifiedClrTypeName} GetMemberInstance(global::GraphQL.IResolveFieldContext context) => _getMemberInstance(context);");
            sb.AppendLine();
        }
    }

    private static void GenerateConstructFieldMethods(
        SourceBuilder sb,
        OutputGraphTypeData outputGraphType)
    {
        for (int i = 0; i < outputGraphType.SelectedMembers.Count; i++)
        {
            var member = outputGraphType.SelectedMembers[i];

            if (!member.IsStatic && outputGraphType.IsInterface)
            {
                // Skip instance members for interfaces
                continue;
            }

            sb.AppendLine($"public void ConstructField{i}_{member.MemberName}(global::GraphQL.Types.FieldType fieldType, global::System.Reflection.MemberInfo memberInfo)");
            sb.AppendLine("{");

            using (sb.Indent())
            {
                if (member.MemberKind == MemberKind.Method)
                {
                    GenerateMethodResolver(sb, member, outputGraphType);
                }
                else
                {
                    GeneratePropertyOrFieldResolver(sb, member, outputGraphType);
                }
            }

            sb.AppendLine("}");
            sb.AppendLine();
        }
    }

    private static void GenerateMethodResolver(
        SourceBuilder sb,
        OutputMemberData member,
        OutputGraphTypeData outputGraphType)
    {
        if (member.MethodParameters.Count > 0)
        {
            // Declare method parameters
            sb.AppendLine("var parameters = ((global::System.Reflection.MethodInfo)memberInfo).GetParameters();");

            for (int i = 0; i < member.MethodParameters.Count; i++)
            {
                var param = member.MethodParameters[i];
                // Use fully qualified type name
                sb.AppendLine($"var param{i} = BuildArgument<{param.FullyQualifiedTypeName}>(fieldType, parameters[{i}]);");
            }
        }

        // Build resolver - different for source stream resolvers
        if (member.IsSourceStreamResolver)
        {
            sb.AppendLine("fieldType.Resolver = global::GraphQL.Resolvers.SourceFieldResolver.Instance;");
            sb.AppendLine("fieldType.StreamResolver = BuildSourceStreamResolver(context =>");
        }
        else
        {
            sb.AppendLine("fieldType.Resolver = BuildFieldResolver(context =>");
        }

        sb.AppendLine("{");

        using (sb.Indent())
        {
            if (member.IsStatic)
            {
                // Static method call - use fully qualified type name
                var declaringType = member.DeclaringTypeFullyQualifiedName ?? outputGraphType.FullyQualifiedClrTypeName;

                if (member.MethodParameters.Count > 0)
                {
                    // Build argument list
                    for (int i = 0; i < member.MethodParameters.Count; i++)
                    {
                        sb.AppendLine($"var arg{i} = param{i}(context);");
                    }
                    var args = string.Join(", ", Enumerable.Range(0, member.MethodParameters.Count).Select(i => $"arg{i}"));
                    sb.AppendLine($"return {declaringType}.{member.MemberName}({args});");
                }
                else
                {
                    sb.AppendLine($"return {declaringType}.{member.MemberName}();");
                }
            }
            else
            {
                // Instance method call
                sb.AppendLine("var source = GetMemberInstance(context);");

                if (member.MethodParameters.Count > 0)
                {
                    // Build argument list
                    for (int i = 0; i < member.MethodParameters.Count; i++)
                    {
                        sb.AppendLine($"var arg{i} = param{i}(context);");
                    }
                    var args = string.Join(", ", Enumerable.Range(0, member.MethodParameters.Count).Select(i => $"arg{i}"));
                    sb.AppendLine($"return source.{member.MemberName}({args});");
                }
                else
                {
                    sb.AppendLine($"return source.{member.MemberName}();");
                }
            }
        }

        if (member.IsSourceStreamResolver)
        {
            sb.AppendLine("});");
        }
        else
        {
            sb.AppendLine("}, true);");
        }
    }

    private static void GeneratePropertyOrFieldResolver(
        SourceBuilder sb,
        OutputMemberData member,
        OutputGraphTypeData outputGraphType)
    {
        if (member.IsStatic)
        {
            // Static property/field access - use fully qualified type name
            var declaringType = member.DeclaringTypeFullyQualifiedName ?? outputGraphType.FullyQualifiedClrTypeName;
            sb.AppendLine($"fieldType.Resolver = BuildFieldResolver(context => {declaringType}.{member.MemberName}, false);");
        }
        else
        {
            // Instance property/field access
            sb.AppendLine($"fieldType.Resolver = BuildFieldResolver(context => GetMemberInstance(context).{member.MemberName}, false);");
        }
    }
}
