federation_version: 1
subgraphs:
  sample1:
    routing_url: http://localhost:5601/graphql
    schema:
      subgraph_url: http://localhost:5601/graphql
  sample2:
    routing_url: http://localhost:5602/graphql
    schema:
      subgraph_url: http://localhost:5602/graphql
